Creating support for Jaleco JF11/JF14 (Mapper 140)
higan-emu/ares pull request #107
Opened 2021-08-26 19:15 UTC by Shideravan

Now the following games are supported in ares:

* Youkai Club: https://youtu.be/ol3mdaTrao8
* Mississippi Satsujin Jiken: https://youtu.be/9zmvD8aFvhE
* Bio Senshi Dan - Increaser Tono Tatakai: https://youtu.be/eiSniHKkfLI

There's a few graphical errors in _Bio Senshi Dan - Increaser Tono Tatakai_ (eg.: the title screen), but I'm unsure it's mapper related.

2021-08-27 08:12 UTC, LukeUsher commented
I'm not sure this implementation is correct? 

This mapper doesn't support CHR RAM, and it doesn't support save ram either; yet your implementation defines/loads both, and implements CHR RAM.

See:
https://wiki.nesdev.com/w/index.php?title=INES_Mapper_140
http://bootgod.dyndns.org:7777/profile.php?id=3966
http://bootgod.dyndns.org:7777/profile.php?id=1548

2021-08-27 14:10 UTC, Shideravan commented
Yes, you're right. Fixed!

2021-08-31 12:06 UTC, LukeUsher requested changes

2021-08-31 12:06 UTC, LukeUsher commented on ares/fc/cartridge/board/jaleco-jf11-jf14.cpp
> +  Memory::Writable<n8> programRAM;
this mapper doesn't have programRAM?

2021-08-31 12:06 UTC, LukeUsher commented on ares/fc/cartridge/board/jaleco-jf11-jf14.cpp
> +    Interface::load(programRAM, "save.ram");
same here, no program ram

2021-08-31 13:22 UTC, Shideravan commented on ares/fc/cartridge/board/jaleco-jf11-jf14.cpp
> +  Memory::Writable<n8> programRAM;
removed

2021-08-31 13:22 UTC, Shideravan commented on ares/fc/cartridge/board/jaleco-jf11-jf14.cpp
> +    Interface::load(programRAM, "save.ram");
Removed

2021-08-31 13:28 UTC, LukeUsher commented on ares/fc/cartridge/board/jaleco-jf11-jf14.cpp
> +    address = characterBank << 13 | (n13)address;
this check can go; address is not used after this so assigning/calculating a banked address is wasteful

2021-08-31 13:47 UTC, LukeUsher approved these changes

2021-08-31 13:50 UTC, merged